name: Setup TypeScript environment
description: Sets up the TypeScript environment with Node.js and pnpm.
branding:
  color: blue
  icon: tool

inputs:
  # pnpm/action-setup
  pnpm-version:
    # See https://github.com/pnpm/action-setup#version for more details
    description: Version of pnpm to install.

  # actions/setup-node
  node-version:
    # See https://github.com/actions/setup-node#supported-version-syntax for more details.
    description: 'Version Spec of the Node.js version to use. Examples: 12.x, 10.15.1, >=10.15.0.'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash