name: Setup TypeScript environment
description: Sets up the TypeScript environment with Node.js and pnpm.
branding:
  color: blue
  icon: box

inputs:
  skip-checkout:
    description: Skip the checkout step
    default: 'false'

  working-directory:
    description: Working directory in which to execute the commands

  # pnpm/action-setup
  pnpm-version:
    # See https://github.com/pnpm/action-setup#version for more details
    description: Version of pnpm to install.

  # actions/setup-node
  node-version:
    # See https://github.com/actions/setup-node#supported-version-syntax for more details.
    description: "Version Spec of the Node.js version to use. Examples: 12.x, 10.15.1, >=10.15.0."

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      working-directory: ${{ inputs.working-directory }}      
      if: inputs.skip-checkout != 'true'
    - name: Setup pnpm
      working-directory: ${{ inputs.working-directory }}        
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Set Node.js version
      working-directory: ${{ inputs.working-directory }}      
      shell: bash
      id: find-node-version
      run: ./get_version.sh ${{ inputs.node-version }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.find-node-version.outputs.NODE_VERSION }}
        cache: pnpm
      working-directory: ${{ inputs.working-directory }}        
    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}  
      shell: bash
      run: pnpm install --frozen-lockfile
