name: Test Action
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test_version_inference:
    name: Test version inference from package.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add dummy package.json
        shell: bash
        run: |
          cp tests/inference.json package.json;
          cp tests/inference.yaml pnpm-lock.yaml;
      - name: Run the action
        uses: ./
        with:
          skip-checkout: true
      - name: Validate pnpm version
        shell: bash
        run: pnpm -v | grep -q '7.10.0' && exit 0
      - name: Validate Node.js version
        shell: bash
        run: node -v | grep -q '18.6.0' && exit 0
